In [2]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader

In [6]:
device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')
print(f"Using device: {device}")

Using device: cpu


In [7]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )
    
    def forward(self, x):
        flat_x = self.flatten(x)
        logits = self.relu_stack(flat_x)
        return logits

In [11]:
model = NeuralNetwork().to(device) # to(.) is redundent if using CPU since default is on CPU. To move all the weights, buffers, biases, etc. to the device.
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=10, bias=True)
  )
)


In [ ]:
X = torch.randn(1, 28, 28).to(device) # to(.) is redundent if using CPU since default is on CPU. To move all the weights, buffers, biases, etc. to the device.
logits = model(X)
print(logits)
pred_probs = nn.Softmax(dim=1)(logits)
print(pred_probs)
y_pred = pred_probs.argmax(1)
print(y_pred)

tensor([[-0.1664, -0.0697,  0.0153, -0.1827, -0.1532,  0.1796, -0.0358, -0.0454,
         -0.1020,  0.0573]], grad_fn=<AddmmBackward0>)
tensor([[0.0885, 0.0975, 0.1062, 0.0871, 0.0897, 0.1251, 0.1009, 0.0999, 0.0944,
         0.1107]], grad_fn=<SoftmaxBackward0>)
tensor([5])
